"""视频表更改带图片

Revision ID: e0c1d81b05b6
Revises: b045c2c510cf
Create Date: 2017-11-17 19:12:38.865381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c1d81b05b6'
down_revision = 'b045c2c510cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('img_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'img_name')
    # ### end Alembic commands ###
